# ---------------------------------------------------------------------------
# DigitalOcean / medium / cluster layer
#
# A QA environment: multi-node, with the two data services whose managed
# behaviour differs most from a pod moved onto managed clusters.
#
# PostgreSQL and Valkey are managed here because both change how the application
# must connect — managed PostgreSQL enforces TLS and hands out a generated
# credential, managed Valkey enforces TLS with an AUTH token. Testing against
# pods hides exactly those differences. MongoDB and Meilisearch stay in-cluster,
# because their managed equivalents behave the same way from the client's side
# and cost considerably more.
#
# Passwords for managed clusters are GENERATED by DigitalOcean rather than
# supplied, so they are read back out and passed to the workload layer through
# state. That is the opposite of the AWS blueprints, where passwords are inputs.
#
# Apply order:
#   1. digitalocean/bootstrap
#   2. digitalocean/environments/medium/cluster
#   3. digitalocean/environments/medium/workload
# ---------------------------------------------------------------------------

terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.43"
    }
  }
  required_version = ">= 1.8.0"
}

provider "digitalocean" {}

locals {
  cluster_name = "${var.project}-${var.tier}"

  tags = [
    "project:${var.project}",
    "tier:${var.tier}",
    "managed-by:terraform",
  ]
}

module "doks" {
  source = "../../../../modules/digitalocean/doks"

  cluster_name       = local.cluster_name
  region             = var.region
  kubernetes_version = var.kubernetes_version

  create_vpc   = true
  vpc_ip_range = var.vpc_ip_range

  node_size  = var.node_size
  node_count = var.node_count
  auto_scale = false

  # Still a paid add-on, and QA can tolerate a control-plane upgrade blip.
  high_availability = false

  destroy_associated_resources = true

  tags = local.tags
}

# ---------------------------------------------------------------------------
# Managed PostgreSQL
# ---------------------------------------------------------------------------
module "postgres" {
  source = "../../../../modules/digitalocean/database"

  name           = "${local.cluster_name}-pg"
  engine         = "pg"
  engine_version = var.postgres_version
  size           = var.postgres_size
  region         = var.region
  node_count     = 1

  vpc_uuid                       = module.doks.vpc_uuid
  allowed_kubernetes_cluster_ids = [module.doks.cluster_id]

  database_name = var.postgres_database
  app_username  = var.postgres_username

  tags = local.tags
}

# ---------------------------------------------------------------------------
# Managed Valkey
#
# No named database or user — Valkey is a single keyspace authenticated with the
# cluster password.
# ---------------------------------------------------------------------------
module "valkey" {
  source = "../../../../modules/digitalocean/database"

  name           = "${local.cluster_name}-valkey"
  engine         = "valkey"
  engine_version = var.valkey_version
  size           = var.valkey_size
  region         = var.region
  node_count     = 1

  vpc_uuid                       = module.doks.vpc_uuid
  allowed_kubernetes_cluster_ids = [module.doks.cluster_id]

  eviction_policy = "allkeys_lru"

  tags = local.tags
}
