# ---------------------------------------------------------------------------
# Consumed by the workload layer. Same shape across all three tiers; anything
# this tier runs in-cluster instead is reported as null.
# ---------------------------------------------------------------------------

output "project" {
  value = var.project
}

output "tier" {
  value = var.tier
}

output "region" {
  value = module.doks.region
}

# --- Cluster ---------------------------------------------------------------
output "cluster_id" {
  value = module.doks.cluster_id
}

output "cluster_name" {
  value = module.doks.cluster_name
}

output "cluster_endpoint" {
  value = module.doks.endpoint
}

output "cluster_ca_certificate" {
  value = module.doks.cluster_ca_certificate
}

output "vpc_uuid" {
  value = module.doks.vpc_uuid
}

output "kubeconfig_command" {
  value = module.doks.kubeconfig_command
}

# --- Managed PostgreSQL ----------------------------------------------------
output "postgres_host" {
  value = module.postgres.host
}

output "postgres_port" {
  value = module.postgres.port
}

output "postgres_database" {
  value = module.postgres.database_name
}

output "postgres_username" {
  value     = module.postgres.username
  sensitive = true
}

output "postgres_password" {
  description = "Generated by DigitalOcean; the workload layer writes it into a Kubernetes Secret"
  value       = module.postgres.password
  sensitive   = true
}

# --- Managed Valkey --------------------------------------------------------
output "valkey_host" {
  value = module.valkey.host
}

output "valkey_port" {
  value = module.valkey.port
}

output "valkey_password" {
  value     = module.valkey.password
  sensitive = true
}

# --- In-cluster at this tier -----------------------------------------------
output "mongodb_host" {
  value = null
}

output "mongodb_port" {
  value = null
}

output "mongodb_database" {
  value = null
}

output "mongodb_username" {
  value     = null
  sensitive = true
}

output "mongodb_password" {
  value     = null
  sensitive = true
}

output "opensearch_host" {
  value = null
}

output "opensearch_port" {
  value = null
}

output "opensearch_username" {
  value     = null
  sensitive = true
}

output "opensearch_password" {
  value     = null
  sensitive = true
}
