variable "project" {
  type    = string
  default = "reactory"
}

variable "tier" {
  type    = string
  default = "medium"
}

variable "region" {
  type    = string
  default = "nyc3"
}

variable "kubernetes_version" {
  description = "Exact DOKS version slug; keep equal to large so upgrades rehearse here"
  type        = string
  default     = "1.31.1-do.0"
}

variable "vpc_ip_range" {
  description = "Distinct from small (10.10) and large (10.12) so tiers can be peered"
  type        = string
  default     = "10.11.0.0/16"
}

# ---------------------------------------------------------------------------
# Nodes
# ---------------------------------------------------------------------------
variable "node_size" {
  description = "Worker Droplet slug. MongoDB and Meilisearch still run in-cluster here."
  type        = string
  default     = "s-2vcpu-4gb"
}

variable "node_count" {
  description = "Two nodes, so PDBs and rolling updates behave as they will at large"
  type        = number
  default     = 2
}

# ---------------------------------------------------------------------------
# Managed data services — smallest sizes that still exercise each engine
# ---------------------------------------------------------------------------
variable "postgres_version" {
  type    = string
  default = "16"
}

variable "postgres_size" {
  description = "db-s-1vcpu-1gb is the smallest managed database node available"
  type        = string
  default     = "db-s-1vcpu-1gb"
}

variable "postgres_database" {
  type    = string
  default = "reactory"
}

variable "postgres_username" {
  description = <<-EOT
    Application user created on the managed cluster. Not a secret — the password
    is generated by DigitalOcean and read back from the provider.
  EOT
  type        = string
  default     = "reactory"
}

variable "valkey_version" {
  type    = string
  default = "8"
}

variable "valkey_size" {
  type    = string
  default = "db-s-1vcpu-1gb"
}
