output "cluster_id" {
  value = digitalocean_database_cluster.this.id
}

output "host" {
  description = <<-EOT
    Private hostname, reachable only from inside the VPC. Prefer this over
    `public_host` — traffic stays on the private network and is not billed as
    egress.
  EOT
  value       = digitalocean_database_cluster.this.private_host
}

output "public_host" {
  description = "Public hostname. Reachable from anywhere the firewall permits."
  value       = digitalocean_database_cluster.this.host
}

output "port" {
  value = digitalocean_database_cluster.this.port
}

output "database_name" {
  description = "Created database name, or the engine's default when none was requested"
  value = (
    length(digitalocean_database_db.this) > 0
    ? digitalocean_database_db.this[0].name
    : digitalocean_database_cluster.this.database
  )
}

# ---------------------------------------------------------------------------
# Credentials
#
# Sensitive: these are generated by DigitalOcean, so unlike the AWS blueprints
# — where passwords are inputs — they can only be discovered by reading them
# back out of the provider, and they land in Terraform state either way.
# ---------------------------------------------------------------------------
output "username" {
  description = "Application user if one was created, otherwise the doadmin superuser"
  value = (
    length(digitalocean_database_user.app) > 0
    ? digitalocean_database_user.app[0].name
    : digitalocean_database_cluster.this.user
  )
  sensitive = true
}

output "password" {
  value = (
    length(digitalocean_database_user.app) > 0
    ? digitalocean_database_user.app[0].password
    : digitalocean_database_cluster.this.password
  )
  sensitive = true
}

output "uri" {
  description = "Full connection URI including credentials"
  value       = digitalocean_database_cluster.this.private_uri
  sensitive   = true
}
