apiVersion: {{ .Values.esoApiVersion }}
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  labels:
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/part-of: reactory
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore.serviceAccount.name }}
            namespace: {{ .Values.clusterSecretStore.serviceAccount.namespace }}
