{{- range $es := .Values.externalSecrets }}
---
apiVersion: {{ $.Values.esoApiVersion }}
kind: ExternalSecret
metadata:
  name: {{ $es.name }}
  namespace: {{ $es.namespace }}
  labels:
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/part-of: reactory
spec:
  refreshInterval: {{ $es.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $.Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ $es.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  {{- range $d := $es.data }}
    - secretKey: {{ $d.secretKey }}
      remoteRef:
        key: {{ $es.remoteRef }}
        property: {{ $d.property }}
  {{- end }}
{{- end }}
