# ---------------------------------------------------------------------------
# Linode / medium / workload layer
#
# Requires linode/environments/medium/cluster.
#
# PostgreSQL is a Linode Managed Database; MongoDB, Valkey and Meilisearch are
# pods, because Linode offers no managed equivalent for any of them.
#
# Two Linode-specific notes:
#
#   Storage — LKE ships a default StorageClass called linode-block-storage-retain,
#   which keeps the underlying volume when the PVC is deleted. That is the safer
#   default and the reason to prefer it over linode-block-storage; it also means
#   deleting a PVC leaves a volume still billing.
#
#   Auth — the LKE kubeconfig carries a long-lived service account token rather
#   than a short-lived credential, so the provider uses it directly. There is no
#   Linode equivalent of `doctl ... exec-credential`. The token is cluster-admin
#   and lives in the cluster layer's state.
#
# See aws/environments/dev/workload/main.tf for why the kubernetes and helm
# providers read from terraform_remote_state rather than module outputs.
# ---------------------------------------------------------------------------

terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "~> 4.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.31"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.17"
    }
  }
  required_version = ">= 1.8.0"
}

data "terraform_remote_state" "cluster" {
  backend = "s3"

  config = {
    bucket = var.state_bucket
    key    = "linode/medium/cluster/terraform.tfstate"
    region = "us-east-1"

    endpoints = {
      s3 = var.state_endpoint
    }

    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
  }
}

locals {
  cluster   = data.terraform_remote_state.cluster.outputs
  namespace = "reactory"

  # LKE provides this StorageClass out of the box; "-retain" keeps the volume
  # when the PVC goes away.
  storage_class = "linode-block-storage-retain"

  # In-cluster service addresses — everything is a pod at this tier.
  mongodb_host     = "mongodb.${local.namespace}.svc.cluster.local"
  valkey_host      = "valkey.${local.namespace}.svc.cluster.local"
  meilisearch_host = "http://meilisearch.${local.namespace}.svc.cluster.local:7700"

  # Without a domain the NodeBalancer IP is unknown until after apply, so
  # api_uri_root can be supplied explicitly on a second pass.
  api_uri_root = (
    var.api_uri_root != "" ? var.api_uri_root
    : var.domain_name != "" ? "https://${var.domain_name}"
    : "http://reactory-express-server.${local.namespace}.svc.cluster.local:4000"
  )

  # TLS only makes sense once a domain resolves to the NodeBalancer — the
  # HTTP-01 challenge has to be reachable from the internet.
  tls_enabled = var.domain_name != "" && var.enable_tls
}

provider "linode" {}

provider "kubernetes" {
  host                   = local.cluster.cluster_endpoint
  cluster_ca_certificate = base64decode(local.cluster.cluster_ca_certificate)
  token                  = local.cluster.cluster_token
}

provider "helm" {
  kubernetes {
    host                   = local.cluster.cluster_endpoint
    cluster_ca_certificate = base64decode(local.cluster.cluster_ca_certificate)
    token                  = local.cluster.cluster_token
  }
}

resource "kubernetes_namespace" "reactory" {
  metadata {
    name = local.namespace
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
      "reactory.io/tier"             = local.cluster.tier
    }
  }
}

# ---------------------------------------------------------------------------
# Secrets
#
# Linode has no secrets manager, so Terraform writes the Kubernetes
# Secrets directly. The values therefore live in this layer's state — see the
# security note in modules/kubernetes/app_secrets.
# ---------------------------------------------------------------------------
module "app_secrets" {
  source = "../../../../modules/kubernetes/app_secrets"

  namespace = kubernetes_namespace.reactory.metadata[0].name

  # Self-hosted Mongo, Postgres, Valkey and Meilisearch; no OpenSearch.
  enabled_secrets = ["mongo", "postgres", "valkey", "meili", "grafana", "app"]

  mongo_username = var.mongo_username
  mongo_password = var.mongo_password
  # Generated by Linode, not supplied — read back through the cluster layer's
  # state. Note this is the ROOT account: Linode Managed Databases expose no
  # user management, so there is no separate application user to use instead.
  postgres_username      = local.cluster.postgres_username
  postgres_password      = local.cluster.postgres_password
  valkey_auth_token      = var.valkey_auth_token
  meilisearch_master_key = var.meilisearch_master_key
  grafana_admin_password = var.grafana_admin_password
  app_secret_key         = var.app_secret_key

  registry_auth = var.registry_auth
}

# ---------------------------------------------------------------------------
# In-cluster data services
# ---------------------------------------------------------------------------
module "mongodb" {
  source = "../../../../modules/kubernetes/mongodb_selfhosted"

  namespace     = kubernetes_namespace.reactory.metadata[0].name
  secret_name   = module.app_secrets.kubernetes_secret_names["mongo"]
  database      = var.mongo_database
  storage_class = local.storage_class
  storage_size  = var.mongodb_storage_size

  depends_on = [module.app_secrets]
}

module "valkey" {
  source = "../../../../modules/kubernetes/valkey_selfhosted"

  namespace   = kubernetes_namespace.reactory.metadata[0].name
  secret_name = module.app_secrets.kubernetes_secret_names["valkey"]

  # A cache that can be rebuilt does not need a volume.
  persistence_enabled = false

  depends_on = [module.app_secrets]
}

module "meilisearch" {
  source = "../../../../modules/kubernetes/meilisearch"

  namespace              = kubernetes_namespace.reactory.metadata[0].name
  master_key_secret_name = module.app_secrets.kubernetes_secret_names["meili"]
  storage_class          = local.storage_class
  storage_size           = var.meilisearch_storage_size
  meili_env              = "development"

  depends_on = [module.app_secrets]
}

# ---------------------------------------------------------------------------
# Ingress
#
# One NodeBalancer is created for the ingress-nginx Service and serves every
# Ingress in the cluster.
# ---------------------------------------------------------------------------
module "ingress_nginx" {
  source = "../../../../modules/kubernetes/ingress_nginx"

  replica_count = 2

  # The Linode CCM turns this Service into a NodeBalancer. TLS terminates at
  # ingress-nginx rather than the NodeBalancer, so cert-manager owns the
  # certificate lifecycle.
  service_annotations = {
    "service.beta.kubernetes.io/linode-loadbalancer-throttle" = "0"
  }

  external_traffic_policy = "Cluster"
  enable_metrics          = true

  enable_cert_manager = local.tls_enabled
  acme_email          = var.acme_email
  acme_server         = var.acme_server
}

# ---------------------------------------------------------------------------
# Observability
# ---------------------------------------------------------------------------
module "observability" {
  source = "../../../../modules/kubernetes/observability"

  grafana_admin_password  = var.grafana_admin_password
  storage_class           = local.storage_class
  prometheus_retention    = "14d"
  prometheus_storage_size = "20Gi"
  install_jaeger          = true
}

# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------
module "reactory_app" {
  source = "../../../../modules/kubernetes/reactory_app"

  namespace   = kubernetes_namespace.reactory.metadata[0].name
  environment = local.cluster.tier

  express_server_image = "${var.image_registry}/${var.express_server_image}:${var.image_tag}"
  pwa_client_image     = "${var.image_registry}/${var.pwa_client_image}:${var.image_tag}"
  image_pull_secrets   = compact([module.app_secrets.registry_secret_name])

  # production, not qa: the point is to exercise the production code path.
  node_env     = "production"
  api_uri_root = local.api_uri_root

  express_server = {
    replicas     = var.express_server_replicas
    max_replicas = var.express_server_max_replicas
  }

  pwa_client = {
    replicas     = var.pwa_client_replicas
    max_replicas = var.pwa_client_max_replicas
  }

  enable_hpa = true
  enable_pdb = true

  # Linode exposes no zone topology label on LKE nodes, so there is nothing to
  # spread across — unlike AWS, where staging and production use this.
  enable_topology_spread = false

  rolling_update = {
    max_surge       = "25%"
    max_unavailable = "0"
  }

  mongo = {
    host        = local.mongodb_host
    database    = var.mongo_database
    secret_name = module.app_secrets.kubernetes_secret_names["mongo"]
    tls         = false
  }

  postgres = {
    host        = local.cluster.postgres_host
    port        = local.cluster.postgres_port
    database    = local.cluster.postgres_database
    secret_name = module.app_secrets.kubernetes_secret_names["postgres"]
  }

  redis = {
    host        = local.valkey_host
    secret_name = module.app_secrets.kubernetes_secret_names["valkey"]
    # The in-cluster Valkey pod does not serve TLS, unlike DigitalOcean's
    # managed Valkey which mandates it.
    tls = false
  }

  search = {
    provider    = "meilisearch"
    endpoint    = local.meilisearch_host
    secret_name = module.app_secrets.kubernetes_secret_names["meili"]
  }

  app_secret = {
    secret_name = module.app_secrets.kubernetes_secret_names["app"]
  }

  ingress = {
    enabled     = true
    class_name  = module.ingress_nginx.ingress_class_name
    domain_name = var.domain_name
    annotations = merge(
      {
        "nginx.ingress.kubernetes.io/proxy-body-size" = "32m"
      },
      local.tls_enabled ? {
        "cert-manager.io/cluster-issuer"                 = module.ingress_nginx.cluster_issuer_name
        "nginx.ingress.kubernetes.io/force-ssl-redirect" = "true"
      } : {},
    )
    tls_secret_name = local.tls_enabled ? "reactory-tls" : null
  }

  labels = { "reactory.io/layer" = "workload" }

  depends_on = [
    module.app_secrets,
    module.ingress_nginx,
    module.mongodb,
    module.valkey,
    module.meilisearch,
  ]
}
