# ---------------------------------------------------------------------------
# DigitalOcean / medium / workload layer
#
# Requires digitalocean/environments/medium/cluster.
#
# PostgreSQL and Valkey are managed clusters here; MongoDB and Meilisearch are
# still pods. Both managed services enforce TLS and hand out generated
# credentials, so this tier exercises the connection behaviour that the small
# tier's pods hide — which is the point of a QA environment.
#
# Two DigitalOcean-specific notes:
#
#   Storage — DOKS ships a default StorageClass called do-block-storage, so
#   unlike the AWS blueprints there is no StorageClass to create. Referencing it
#   by name is enough.
#
#   Auth — the token in digitalocean_kubernetes_cluster.kube_config expires
#   after about a week, so wiring it into the provider produces a configuration
#   that silently stops working. doctl's exec-credential plugin mints a fresh
#   one on every invocation, the same shape as `aws eks get-token`.
#
# See aws/environments/dev/workload/main.tf for why the kubernetes and helm
# providers read from terraform_remote_state rather than module outputs.
# ---------------------------------------------------------------------------

terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.43"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.31"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.17"
    }
  }
  required_version = ">= 1.8.0"
}

data "terraform_remote_state" "cluster" {
  backend = "s3"

  config = {
    bucket = var.state_bucket
    key    = "digitalocean/medium/cluster/terraform.tfstate"
    region = "us-east-1"

    endpoints = {
      s3 = var.state_endpoint
    }

    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
  }
}

locals {
  cluster   = data.terraform_remote_state.cluster.outputs
  namespace = "reactory"

  # DOKS provides this StorageClass out of the box.
  storage_class = "do-block-storage"

  # Still in-cluster at this tier; PostgreSQL and Valkey come from the cluster layer.
  mongodb_host     = "mongodb.${local.namespace}.svc.cluster.local"
  meilisearch_host = "http://meilisearch.${local.namespace}.svc.cluster.local:7700"

  # Without a domain the load balancer IP is unknown until after apply, so
  # api_uri_root can be supplied explicitly on a second pass.
  api_uri_root = (
    var.api_uri_root != "" ? var.api_uri_root
    : var.domain_name != "" ? "https://${var.domain_name}"
    : "http://reactory-express-server.${local.namespace}.svc.cluster.local:4000"
  )

  # TLS only makes sense once a domain resolves to the load balancer — the
  # HTTP-01 challenge has to be reachable from the internet.
  tls_enabled = var.domain_name != "" && var.enable_tls
}

provider "digitalocean" {}

provider "kubernetes" {
  host                   = local.cluster.cluster_endpoint
  cluster_ca_certificate = base64decode(local.cluster.cluster_ca_certificate)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "doctl"
    args        = ["kubernetes", "cluster", "kubeconfig", "exec-credential", "--version=v1beta1", local.cluster.cluster_id]
  }
}

provider "helm" {
  kubernetes {
    host                   = local.cluster.cluster_endpoint
    cluster_ca_certificate = base64decode(local.cluster.cluster_ca_certificate)

    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "doctl"
      args        = ["kubernetes", "cluster", "kubeconfig", "exec-credential", "--version=v1beta1", local.cluster.cluster_id]
    }
  }
}

resource "kubernetes_namespace" "reactory" {
  metadata {
    name = local.namespace
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
      "reactory.io/tier"             = local.cluster.tier
    }
  }
}

# ---------------------------------------------------------------------------
# Secrets
#
# DigitalOcean has no secrets manager, so Terraform writes the Kubernetes
# Secrets directly. The values therefore live in this layer's state — see the
# security note in modules/kubernetes/app_secrets.
# ---------------------------------------------------------------------------
module "app_secrets" {
  source = "../../../../modules/kubernetes/app_secrets"

  namespace = kubernetes_namespace.reactory.metadata[0].name

  # Self-hosted Mongo, Postgres, Valkey and Meilisearch; no OpenSearch.
  enabled_secrets = ["mongo", "postgres", "valkey", "meili", "grafana", "app"]

  mongo_username = var.mongo_username
  mongo_password = var.mongo_password
  # Generated by DigitalOcean, not supplied — read back through the cluster
  # layer's state and written into Kubernetes Secrets here.
  postgres_username      = local.cluster.postgres_username
  postgres_password      = local.cluster.postgres_password
  valkey_auth_token      = local.cluster.valkey_password
  meilisearch_master_key = var.meilisearch_master_key
  grafana_admin_password = var.grafana_admin_password
  app_secret_key         = var.app_secret_key

  registry_auth = var.registry_auth
}

# ---------------------------------------------------------------------------
# In-cluster data services
# ---------------------------------------------------------------------------
module "mongodb" {
  source = "../../../../modules/kubernetes/mongodb_selfhosted"

  namespace     = kubernetes_namespace.reactory.metadata[0].name
  secret_name   = module.app_secrets.kubernetes_secret_names["mongo"]
  database      = var.mongo_database
  storage_class = local.storage_class
  storage_size  = var.mongodb_storage_size

  depends_on = [module.app_secrets]
}

module "meilisearch" {
  source = "../../../../modules/kubernetes/meilisearch"

  namespace              = kubernetes_namespace.reactory.metadata[0].name
  master_key_secret_name = module.app_secrets.kubernetes_secret_names["meili"]
  storage_class          = local.storage_class
  storage_size           = var.meilisearch_storage_size
  meili_env              = "development"

  depends_on = [module.app_secrets]
}

# ---------------------------------------------------------------------------
# Ingress
#
# One DigitalOcean Load Balancer serves every Ingress in the cluster. Two
# controller replicas so a node drain does not drop all ingress.
# ---------------------------------------------------------------------------
module "ingress_nginx" {
  source = "../../../../modules/kubernetes/ingress_nginx"

  replica_count = 2

  service_annotations = {
    "service.beta.kubernetes.io/do-loadbalancer-name" = "${local.cluster.cluster_name}-lb"
    # Terminate TLS at ingress-nginx rather than the load balancer, so
    # cert-manager owns the certificate lifecycle.
    "service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol" = "false"
    "service.beta.kubernetes.io/do-loadbalancer-size-unit"             = "1"
  }

  external_traffic_policy = "Cluster"
  enable_metrics          = true

  enable_cert_manager = local.tls_enabled
  acme_email          = var.acme_email
  acme_server         = var.acme_server
}

# ---------------------------------------------------------------------------
# Observability
# ---------------------------------------------------------------------------
module "observability" {
  source = "../../../../modules/kubernetes/observability"

  grafana_admin_password  = var.grafana_admin_password
  storage_class           = local.storage_class
  prometheus_retention    = "14d"
  prometheus_storage_size = "20Gi"
  install_jaeger          = true
}

# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------
module "reactory_app" {
  source = "../../../../modules/kubernetes/reactory_app"

  namespace   = kubernetes_namespace.reactory.metadata[0].name
  environment = local.cluster.tier

  express_server_image = "${var.image_registry}/${var.express_server_image}:${var.image_tag}"
  pwa_client_image     = "${var.image_registry}/${var.pwa_client_image}:${var.image_tag}"
  image_pull_secrets   = compact([module.app_secrets.registry_secret_name])

  # production, not qa: the point is to exercise the production code path.
  node_env     = "production"
  api_uri_root = local.api_uri_root

  express_server = {
    replicas     = var.express_server_replicas
    max_replicas = var.express_server_max_replicas
  }

  pwa_client = {
    replicas     = var.pwa_client_replicas
    max_replicas = var.pwa_client_max_replicas
  }

  enable_hpa = true
  enable_pdb = true

  # DOKS node pools sit in one region but DigitalOcean exposes no zone topology
  # label, so there is nothing to spread across. This stays false on every
  # DigitalOcean tier — unlike AWS, where staging and production use it.
  enable_topology_spread = false

  rolling_update = {
    max_surge       = "25%"
    max_unavailable = "0"
  }

  mongo = {
    host        = local.mongodb_host
    database    = var.mongo_database
    secret_name = module.app_secrets.kubernetes_secret_names["mongo"]
    tls         = false
  }

  postgres = {
    host        = local.cluster.postgres_host
    port        = local.cluster.postgres_port
    database    = local.cluster.postgres_database
    secret_name = module.app_secrets.kubernetes_secret_names["postgres"]
  }

  redis = {
    host        = local.cluster.valkey_host
    port        = local.cluster.valkey_port
    secret_name = module.app_secrets.kubernetes_secret_names["valkey"]
    # Managed Valkey mandates TLS.
    tls = true
  }

  search = {
    provider    = "meilisearch"
    endpoint    = local.meilisearch_host
    secret_name = module.app_secrets.kubernetes_secret_names["meili"]
  }

  app_secret = {
    secret_name = module.app_secrets.kubernetes_secret_names["app"]
  }

  ingress = {
    enabled     = true
    class_name  = module.ingress_nginx.ingress_class_name
    domain_name = var.domain_name
    annotations = merge(
      {
        "nginx.ingress.kubernetes.io/proxy-body-size" = "32m"
      },
      local.tls_enabled ? {
        "cert-manager.io/cluster-issuer"                 = module.ingress_nginx.cluster_issuer_name
        "nginx.ingress.kubernetes.io/force-ssl-redirect" = "true"
      } : {},
    )
    tls_secret_name = local.tls_enabled ? "reactory-tls" : null
  }

  labels = { "reactory.io/layer" = "workload" }

  depends_on = [
    module.app_secrets,
    module.ingress_nginx,
    module.mongodb,
    module.meilisearch,
  ]
}
